#[allow(dead_code)]
pub fn generate_metric_lines() -> Vec<String> {
    vec![
        "# HELP metric_1 Description of the metric".to_string(),
        "# TYPE metric_1 gauge".to_string(),
        "metric_1{shard=\"0\"} 10.0".to_string(),
        "# HELP metric_2 Description".to_string(),
        "# TYPE metric_2 counter".to_string(),
        "metric_2{shard=\"0\",label1=\"test1\"} 5".to_string(),
        "# HELP incoming_requests Incoming Requests".to_string(),
        "# TYPE incoming_requests counter".to_string(),
        "incoming_requests 10".to_string(),
        "# HELP connected_clients Connected Clients".to_string(),
        "# TYPE connected_clients gauge".to_string(),
        "connected_clients 3".to_string(),
        "# HELP response_time Response Times".to_string(),
        "# TYPE response_time histogram".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.005\"} 3".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.01\"} 4".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.025\"} 13".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.05\"} 25".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.1\"} 57".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.25\"} 148".to_string(),
        "response_time_bucket{env=\"production\",le=\"0.5\"} 319".to_string(),
        "response_time_bucket{env=\"production\",le=\"+Inf\"} 6563".to_string(),
        "response_time_sum{env=\"production\"} 32899.06535799631".to_string(),
        "response_time_count{env=\"production\"} 6563".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.005\"} 4".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.01\"} 4".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.025\"} 13".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.05\"} 31".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.1\"} 56".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.25\"} 168".to_string(),
        "response_time_bucket{env=\"testing\",le=\"0.5\"} 338".to_string(),
        "response_time_bucket{env=\"testing\",le=\"+Inf\"} 6451".to_string(),
        "response_time_sum{env=\"testing\"} 32157.055112958977".to_string(),
        "response_time_count{env=\"testing\"} 6451".to_string(),
        "# HELP response_time_no_labels Response Times".to_string(),
        "# TYPE response_time_no_labels  histogram".to_string(),
        "response_time_no_labels_bucket{le=\"0.005\"} 3".to_string(),
        "response_time_no_labels_bucket{le=\"0.01\"} 4".to_string(),
        "response_time_no_labels_bucket{le=\"0.025\"} 13".to_string(),
        "response_time_no_labels_bucket{le=\"0.05\"} 25".to_string(),
        "response_time_no_labels_bucket{le=\"0.1\"} 57".to_string(),
        "response_time_no_labels_bucket{le=\"0.25\"} 148".to_string(),
        "response_time_no_labels_bucket{le=\"0.5\"} 319".to_string(),
        "response_time_no_labels_bucket{le=\"+Inf\"} 6563".to_string(),
        "response_time_no_labels_sum 32899.06535799631".to_string(),
        "response_time_count 6451".to_string(),
    ]
}
